# Generated by Django 3.0.2 on 2020-03-24 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 7, 20, 12, 279833, tzinfo=utc)),
        ),
    ]
