# Generated by Django 3.0.2 on 2020-03-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200324_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clap',
            name='no_of_claps',
        ),
        migrations.AddField(
            model_name='clap',
            name='myblog',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.blog'),
        ),
    ]
