# Generated by Django 3.0.2 on 2020-03-29 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='claps',
            field=models.ManyToManyField(blank=True, related_name='clappers', to=settings.AUTH_USER_MODEL),
        ),
    ]
