# Generated by Django 3.0.2 on 2020-04-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_profile_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='Just a cool blog', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Just a cool blog', max_length=300),
        ),
    ]
